#+TITLE: Carta de Presentación
#+AUTHOR: Rigel Valencia Osorio
#+DATE: Julio de 2026
#+LANGUAGE: es
#+OPTIONS: toc:nil num:nil

#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [12pt, a4paper]
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage[spanish]{babel}
#+LATEX_HEADER: \usepackage{libertine}
#+LATEX_HEADER: \usepackage{geometry}
#+LATEX_HEADER: \geometry{a4paper, left=3cm, right=2.5cm, top=3cm, bottom=2.5cm}
#+LATEX_HEADER: \pagestyle{empty}

\vspace*{2cm}

\begin{flushright}
Manizales, Caldas\\
Julio de 2026
\end{flushright}

\vspace{1cm}

\begin{flushleft}
Señores\\
\textbf{Grupo de Investigación Tántalo}\\
Departamento de Filosofía\\
Universidad de Caldas
\end{flushleft}

\vspace{1cm}

\textbf{Asunto: Postulación como Sabedor — Presentación de ensayo filosófico}

\vspace{0.5cm}

Estimados miembros del Grupo Tántalo:

\vspace{0.3cm}

Mi nombre es Rigel Valencia Osorio, músico e investigador independiente
de Manizales. Me dirijo a ustedes con el propósito de postularme bajo
la figura institucional de Sabedor, contemplada en los reglamentos de
la Universidad de Caldas, para continuar y formalizar mis estudios
avanzados dentro del Departamento de Filosofía.

Mi línea de trabajo se sitúa en la intersección entre la filosofía de
la música, la ontología materialista y la praxis tecnológica mediante
software libre. Durante los últimos meses he desarrollado un ensayo
titulado \textit{Hacia una Ontología Materialista de la Música desde la
Experiencia Vital}, que adjunto a esta carta. El documento —de
aproximadamente 70 páginas— propone una visión de la música como
laboratorio filosófico donde se verifican tesis sobre la discontinuidad
de la materia, el entrelazamiento de géneros (\textit{symploké}) y la
crítica al idealismo subjetivista, a partir del materialismo filosófico
de Gustavo Bueno y Vicente Chuliá.

El ensayo dialoga directamente con las líneas de investigación en
Estética y Filosofía del Arte del Grupo Tántalo, e incorpora una
genealogía del saber musical que va de los presocráticos a la Nueva
Complejidad, una crítica a la fragmentación de la educación actual, y
una defensa del software libre como infraestructura de soberanía
tecnológica. Todo el proceso de escritura, los códigos fuente y las
versiones intermedias están disponibles en un repositorio público:

\begin{center}
\texttt{https://github.com/rigelsimploke/symploke-sonora}
\end{center}

Solicito respetuosamente que este material sea evaluado por un comité
curricular para considerar la convalidación de mis aprendizajes previos
y trazar una ruta formativa continua dentro del Departamento. Estoy a
su disposición para una entrevista técnica o para ampliar cualquier
aspecto de mi trayectoria o de mi trabajo.

Agradezco de antemano su atención y quedo atento a sus orientaciones.

\vspace{1cm}

\begin{flushright}
Cordialmente,\\[1em]
Rigel Valencia Osorio\\
3027170172\\
jazzmebluesrigel@gmail.com
\end{flushright}
